index:
    path: /
    methods: POST
    controller: App\Controller\Controller::index

doctor_add:
    path: /doctor
    methods: POST
    controller: App\Controller\Controller::addDoctorController

doctor_get:
    path: /doctor
    methods: GET
    controller: App\Controller\Controller::getDoctorController

slots_add:
    path: /slots/{doctorId}
    methods: POST
    controller: App\Controller\Controller::addSlotController

slots_get:
    path: /slots/{doctorId}
    methods: GET
    controller: App\Controller\Controller::getSlotController
